// Load configuration from environment
const SUPABASE_URL = 'https://vilpzhxvrqidjvyifhuz.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbHB6aHh2cnFpZGp2eWlmaHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MDg1ODMsImV4cCI6MjA5Mzk4NDU4M30.u3D3ScYjzpg4fpMwV8wrNkWlmuMT4QgWTspsNavAJdk';

const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);